version: "3.8"
services:
  beehive_guard:
    container_name: beehive_guard-container
    build:
      context: ./beehive-guard
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - JAVA_DB_URL=${JAVA_DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
    ports:
      - "${BEEHIVE_GUARD_PORT}:8080"
    depends_on:
      - beehive_postgres
  beehive_nest:
    container_name: beehive_nest-container
    build:
      context: ./beehive-nest
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - JAVA_DB_URL=${JAVA_DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GUARD_SERVICE_URL=http://host.docker.internal:${BEEHIVE_GUARD_PORT}
      - MIND_SERVICE_URL=http://host.docker.internal:8000
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - API_KEY=${API_KEY}
    ports:
      - "${NEST_SERVICE_PORT}:8080"
    depends_on:
      - beehive_postgres
      - beehive_guard
      - beehive_minio
  beehive_mind:
    container_name: beehive_mind-container
    build:
      context: ./beehive-mind
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    ports:
      - "${BEEHIVE_MIND_PORT}:8000"
    depends_on:
      - beehive_minio
  beehive_minio:
    container_name: beehive_minio-container
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  beehive_postgres:
    container_name: beehive_postgres-container
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  minio_data:
  postgres_data:
