services:
  beehive_guard:
    container_name: beehive_guard-container
    build:
      context: ./beehive-guard
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${GUARD_SERVICE_PORT}:8080"
    depends_on:
      - beehive_postgres
  beehive_nest:
    container_name: beehive_nest-container
    build:
      context: ./beehive-nest
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${NEST_SERVICE_PORT}:8080"
    depends_on:
      - beehive_postgres
      - beehive_guard
      - beehive_minio
  beehive_mind:
    container_name: beehive_mind-container
    build:
      context: ./beehive-mind
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${MIND_SERVICE_PORT}:8000"
    depends_on:
      - beehive_minio
  beehive_minio:
    container_name: beehive_minio-container
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file: .env
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  beehive_postgres:
    container_name: beehive_postgres-container
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  minio_data:
  postgres_data:
