version: '3.8'
services:
  beehive_guard:
    container_name: beehive_guard-container
    build:
      context: ./beehive-guard
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/
      - DB_USER=
      - DB_PASSWORD=
      - JWT_SECRET=
      - API_KEY=
    ports:
      - "8852:8080"
  beehive_nest:
    container_name: beehive_nest-container
    build:
      context: ./beehive-nest
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/
      - DB_USER=
      - DB_PASSWORD=
      - GUARD_SERVICE_URL=http://host.docker.internal:8852
      - MIND_SERVICE_URL=http://host.docker.internal:9000
      - S3_ENDPOINT=http://host.docker.internal:9000
      - S3_ACCESS_KEY=
      - S3_SECRET_KEY=
      - API_KEY=
    ports:
      - "8080:8080"
    depends_on:
      - beehive_guard
      - beehive_minio
  beehive_minio:
    container_name: beehive_minio-container
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
volumes:
  minio_data:

